enum RECIPE {
  VIEW_RECIPE = 'VIEW_RECIPE',
  EXIT_RECIPE = 'EXIT_RECIPE',
  SET_RECIPES = 'SET_RECIPES',
}

enum SEARCH {
  SET_QUERY = 'SET_QUERY',
  SET_DIETS = 'SET_DIETS',
  SET_TYPES = 'SET_TYPES',
  SET_CUISINES = 'SET_CUISINES',
  SET_INTOLERANCES = 'SET_INTOLERANCES'
}

export {
  RECIPE,
  SEARCH
}